name: Auto Bump Version, Build and Push Docker Image to Harbor

on:
  push:
    branches:
      - master
      - dev

jobs:
  bump-build-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    env:
      HARBOR_REGISTRY: harbor.jbnu.ac.kr
      HARBOR_PROJECT: jinseok1006
      IMAGE_NAME: semver-test

    steps:
      - uses: actions/checkout@v4

      - id: tag_version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          PRERELEASE: true
          PRE_RELEASE_BRANCHES: dev

      - name: Set version to environment
        run: echo "VERSION=${{ steps.tag_version.outputs.new_tag }}" >> $GITHUB_ENV

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
