# .github/workflows/auto-tag.yml
name: Auto Tag on Push

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: anothrNick/github-tag-action@v1.71.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch       # 기본은 patch 증가 (커밋 메시지 없으면)
          WITH_V: true              # 태그에 v 접두어 붙이기 (v1.2.3)
          RELEASE_BRANCHES: main    # main 브랜치만 릴리즈로 처리
